name: 'Build docker image'
on: [push]
jobs:
  build:
    name: 'Build docker image'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
        run:
          shell: bash

    steps:
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
    - name: 'Checkout the repository to the GitHub Actions runner'

    # Set up QEMU
    - uses: docker/setup-qemu-action@v1
    - name: 'Set up QEMU'

    # Login to DockerHub with username and token
    - uses: docker/login-action@v1
    - name: Login to DockerHub with username and token
    - with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build image and push to DockerHub
    - uses: docker/build-push-action@v2
    - name: "Build image and push to DockerHub"
    - with:
        context: .
        push: true
        tags: sbilly/zerotier-controller:latest
    
